print("-------------------")
print("First test: Compact")
print("-------------------")

# 5' to 3' Frame: 0
logic = "MTEYKLVVVGDGGVGKSALTIQLIQNHFVEEYDPTIEDSYRKQVVIDGETCLLDILDTAGQEEYSAMRDQYMRTGEGFLLVFAVNEAKSFENVANYREQIRRVKDSDDVPMVLVGNKCDLSSRSVDFRTVSETAKGYGIPNVDTSAKTRMGVDEAFYTLVREIRKHRERHDNNKPQKKKKCQIM-" == "MTEYKLVVVGDGGVGKSALTIQLIQNHFVEEYDPTIEDSYRKQVVIDGETCLLDILDTAGQEEYSAMRDQYMRTGEGFLLVFAVNEAKSFENVANYREQIRRVKDSDDVPMVLVGNKCDLSSRSVDFRTVSETAKGYGIPNVDTSAKTRMGVDEAFYTLVREIRKHRERHDNNKPQKKKKCQIM-"
print("5' to 3' Frame: 0")
print(logic)

# 5' to 3' Frame: 1
logic = "-RSTSLW-LEMEELVNQHSPFNSSRITLSKNTTRP-RTATESRL--TVRHASSTYWIPPDKKNIRRCVIST-GQAKDFCWFSPSTRLNLSRMSLTTASRFGG-RIQMMFLWSW-GINVICHLDQSTSEQSVRQQRVTVFRMSTHLPKRVWELMKHFTHLLEKFASIVSVTTIISHKRRRSVK-C" == "-RSTSLW-LEMEELVNQHSPFNSSRITLSKNTTRP-RTATESRL--TVRHASSTYWIPPDKKNIRRCVIST-GQAKDFCWFSPSTRLNLSRMSLTTASRFGG-RIQMMFLWSW-GINVICHLDQSTSEQSVRQQRVTVFRMSTHLPKRVWELMKHFTHLLEKFASIVSVTTIISHKRRRSVK-C"
print("5' to 3' Frame: 1")
print(logic)

# 5' to 3' Frame: 2
logic = "DGVQACGSWRWRSW-ISTHHSTHPESLCRRIRPDHRGQLQKAGCDRR-DMPPRHIGYRRTRRIFGDA-SVHEDRRRISVGFRRQRG-IFRECR-LPRADSEGKGFR-CSYGLGRE-M-FVISISRLPNSQ-DSKGLRYSECRHICQNAYGS--SILHTC-RNSQAS-ASRQ--ATKEEEVSNNV" == "DGVQACGSWRWRSW-ISTHHSTHPESLCRRIRPDHRGQLQKAGCDRR-DMPPRHIGYRRTRRIFGDA-SVHEDRRRISVGFRRQRG-IFRECR-LPRADSEGKGFR-CSYGLGRE-M-FVISISRLPNSQ-DSKGLRYSECRHICQNAYGS--SILHTC-RNSQAS-ASRQ--ATKEEEVSNNV"
print("5' to 3' Frame: 2")
print(logic)

# 3' to 5' Frame: 0
logic = "SHYLTLLLLLWLIIVVTLTMLANFSNKCVKCFINSHTRFGRCVDIRNTVTLCCLTDCSEVD-SR-QITFIPYQDHRNII-ILYPPNLLAVVSDILERFSLVDGENQQKSFACPHVLITHRRIFFLSGGIQYVEEACLTVYHNLLSVAVLYGRVVFFDKVILDELNGEC-FTNSSISNYHKLVLRH" == "SHYLTLLLLLWLIIVVTLTMLANFSNKCVKCFINSHTRFGRCVDIRNTVTLCCLTDCSEVD-SR-QITFIPYQDHRNII-ILYPPNLLAVVSDILERFSLVDGENQQKSFACPHVLITHRRIFFLSGGIQYVEEACLTVYHNLLSVAVLYGRVVFFDKVILDELNGEC-FTNSSISNYHKLVLRH"
print("3' to 5' Frame: 0")
print(logic)

# 3' to 5' Frame: 1
logic = "HII-HFFFFCGLLLS-RSRCLRISLTSV-NASSTPIRVLADVSTFGIP-PFAVSLTVRKSTDRDDKSHLFPTKTIGTSSESFTLRICSR-LATFSKDLASLTAKTNRNPSPVLMY-SRIAEYSSCPAVSNMSRRHVSPSITTCFL-LSSMVGSYSSTK-FWMS-MVSADLPTPPSPTTTSLYSV" == "HII-HFFFFCGLLLS-RSRCLRISLTSV-NASSTPIRVLADVSTFGIP-PFAVSLTVRKSTDRDDKSHLFPTKTIGTSSESFTLRICSR-LATFSKDLASLTAKTNRNPSPVLMY-SRIAEYSSCPAVSNMSRRHVSPSITTCFL-LSSMVGSYSSTK-FWMS-MVSADLPTPPSPTTTSLYSV"
print("3' to 5' Frame: 1")
print(logic)

# 3' to 5' Frame: 2
logic = "TLFDTSSSFVAYYCRDAHDACEFL-QVCKMLHQLPYAFWQMCRHSEYRNPLLSH-LFGSRLIEMTNHIYSLPRP-EHHLNPLPSESARGS-RHSRKI-PR-RRKPTEILRLSSCTDHASPNILLVRRYPICRGGMSHRLSQPAFCSCPLWSGRILRQSDSG-VEW-VLIYQLLHLQLPQACTPS" == "TLFDTSSSFVAYYCRDAHDACEFL-QVCKMLHQLPYAFWQMCRHSEYRNPLLSH-LFGSRLIEMTNHIYSLPRP-EHHLNPLPSESARGS-RHSRKI-PR-RRKPTEILRLSSCTDHASPNILLVRRYPICRGGMSHRLSQPAFCSCPLWSGRILRQSDSG-VEW-VLIYQLLHLQLPQACTPS"
print("3' to 5' Frame: 2")
print(logic)

print("-------------------")
print("First test: Verbose")
print("-------------------")

# 5' to 3' Frame: 0
logic = "Met T E Y K L V V V G D G G V G K S A L T I Q L I Q N H F V E E Y D P T I E D S Y R K Q V V I D G E T C L L D I L D T A G Q E E Y S A Met R D Q Y Met R T G E G F L L V F A V N E A K S F E N V A N Y R E Q I R R V K D S D D V P Met V L V G N K C D L S S R S V D F R T V S E T A K G Y G I P N V D T S A K T R Met G V D E A F Y T L V R E I R K H R E R H D N N K P Q K K K K C Q I Met Stop" == "Met T E Y K L V V V G D G G V G K S A L T I Q L I Q N H F V E E Y D P T I E D S Y R K Q V V I D G E T C L L D I L D T A G Q E E Y S A Met R D Q Y Met R T G E G F L L V F A V N E A K S F E N V A N Y R E Q I R R V K D S D D V P Met V L V G N K C D L S S R S V D F R T V S E T A K G Y G I P N V D T S A K T R Met G V D E A F Y T L V R E I R K H R E R H D N N K P Q K K K K C Q I Met Stop"
print("5' to 3' Frame: 0")
print(logic)

# 5' to 3' Frame: 1
logic = "Stop R S T S L W Stop L E Met E E L V N Q H S P F N S S R I T L S K N T T R P Stop R T A T E S R L Stop Stop T V R H A S S T Y W I P P D K K N I R R C V I S T Stop G Q A K D F C W F S P S T R L N L S R Met S L T T A S R F G G Stop R I Q Met Met F L W S W Stop G I N V I C H L D Q S T S E Q S V R Q Q R V T V F R Met S T H L P K R V W E L Met K H F T H L L E K F A S I V S V T T I I S H K R R R S V K Stop C" == "Stop R S T S L W Stop L E Met E E L V N Q H S P F N S S R I T L S K N T T R P Stop R T A T E S R L Stop Stop T V R H A S S T Y W I P P D K K N I R R C V I S T Stop G Q A K D F C W F S P S T R L N L S R Met S L T T A S R F G G Stop R I Q Met Met F L W S W Stop G I N V I C H L D Q S T S E Q S V R Q Q R V T V F R Met S T H L P K R V W E L Met K H F T H L L E K F A S I V S V T T I I S H K R R R S V K Stop C"
print("5' to 3' Frame: 1")
print(logic)

# 5' to 3' Frame: 2
logic = "D G V Q A C G S W R W R S W Stop I S T H H S T H P E S L C R R I R P D H R G Q L Q K A G C D R R Stop D Met P P R H I G Y R R T R R I F G D A Stop S V H E D R R R I S V G F R R Q R G Stop I F R E C R Stop L P R A D S E G K G F R Stop C S Y G L G R E Stop Met Stop F V I S I S R L P N S Q Stop D S K G L R Y S E C R H I C Q N A Y G S Stop Stop S I L H T C Stop R N S Q A S Stop A S R Q Stop Stop A T K E E E V S N N V" == "D G V Q A C G S W R W R S W Stop I S T H H S T H P E S L C R R I R P D H R G Q L Q K A G C D R R Stop D Met P P R H I G Y R R T R R I F G D A Stop S V H E D R R R I S V G F R R Q R G Stop I F R E C R Stop L P R A D S E G K G F R Stop C S Y G L G R E Stop Met Stop F V I S I S R L P N S Q Stop D S K G L R Y S E C R H I C Q N A Y G S Stop Stop S I L H T C Stop R N S Q A S Stop A S R Q Stop Stop A T K E E E V S N N V"
print("5' to 3' Frame: 2")
print(logic)

# 3' to 5' Frame: 0
logic = "S H Y L T L L L L L W L I I V V T L T Met L A N F S N K C V K C F I N S H T R F G R C V D I R N T V T L C C L T D C S E V D Stop S R Stop Q I T F I P Y Q D H R N I I Stop I L Y P P N L L A V V S D I L E R F S L V D G E N Q Q K S F A C P H V L I T H R R I F F L S G G I Q Y V E E A C L T V Y H N L L S V A V L Y G R V V F F D K V I L D E L N G E C Stop F T N S S I S N Y H K L V L R H" == "S H Y L T L L L L L W L I I V V T L T Met L A N F S N K C V K C F I N S H T R F G R C V D I R N T V T L C C L T D C S E V D Stop S R Stop Q I T F I P Y Q D H R N I I Stop I L Y P P N L L A V V S D I L E R F S L V D G E N Q Q K S F A C P H V L I T H R R I F F L S G G I Q Y V E E A C L T V Y H N L L S V A V L Y G R V V F F D K V I L D E L N G E C Stop F T N S S I S N Y H K L V L R H"
print("3' to 5' Frame: 0")
print(logic)

# 3' to 5' Frame: 1
logic = "H I I Stop H F F F F C G L L L S Stop R S R C L R I S L T S V Stop N A S S T P I R V L A D V S T F G I P Stop P F A V S L T V R K S T D R D D K S H L F P T K T I G T S S E S F T L R I C S R Stop L A T F S K D L A S L T A K T N R N P S P V L Met Y Stop S R I A E Y S S C P A V S N Met S R R H V S P S I T T C F L Stop L S S Met V G S Y S S T K Stop F W Met S Stop Met V S A D L P T P P S P T T T S L Y S V" == "H I I Stop H F F F F C G L L L S Stop R S R C L R I S L T S V Stop N A S S T P I R V L A D V S T F G I P Stop P F A V S L T V R K S T D R D D K S H L F P T K T I G T S S E S F T L R I C S R Stop L A T F S K D L A S L T A K T N R N P S P V L Met Y Stop S R I A E Y S S C P A V S N Met S R R H V S P S I T T C F L Stop L S S Met V G S Y S S T K Stop F W Met S Stop Met V S A D L P T P P S P T T T S L Y S V"
print("3' to 5' Frame: 1")
print(logic)

# 3' to 5' Frame: 2
logic = "T L F D T S S S F V A Y Y C R D A H D A C E F L Stop Q V C K Met L H Q L P Y A F W Q Met C R H S E Y R N P L L S H Stop L F G S R L I E Met T N H I Y S L P R P Stop E H H L N P L P S E S A R G S Stop R H S R K I Stop P R Stop R R K P T E I L R L S S C T D H A S P N I L L V R R Y P I C R G G Met S H R L S Q P A F C S C P L W S G R I L R Q S D S G Stop V E W Stop V L I Y Q L L H L Q L P Q A C T P S" == "T L F D T S S S F V A Y Y C R D A H D A C E F L Stop Q V C K Met L H Q L P Y A F W Q Met C R H S E Y R N P L L S H Stop L F G S R L I E Met T N H I Y S L P R P Stop E H H L N P L P S E S A R G S Stop R H S R K I Stop P R Stop R R K P T E I L R L S S C T D H A S P N I L L V R R Y P I C R G G Met S H R L S Q P A F C S C P L W S G R I L R Q S D S G Stop V E W Stop V L I Y Q L L H L Q L P Q A C T P S"
print("3' to 5' Frame: 2")
print(logic)

print("-------------------")
print("First test: DNA")
print("-------------------")

# 5' to 3' Frame: 0
sol = """ATGACGGAGTACAAGCTTGTGGTAGTTGGAGATGGAGGAGTTGGTAAATCAGCACTCACC
          M  T  E  Y  K  L  V  V  V  G  D  G  G  V  G  K  S  A  L  T
         ATTCAACTCATCCAGAATCACTTTGTCGAAGAATACGACCCGACCATAGAGGACAGCTAC
          I  Q  L  I  Q  N  H  F  V  E  E  Y  D  P  T  I  E  D  S  Y
         AGAAAGCAGGTTGTGATAGACGGTGAGACATGCCTCCTCGACATATTGGATACCGCCGGA
          R  K  Q  V  V  I  D  G  E  T  C  L  L  D  I  L  D  T  A  G
         CAAGAAGAATATTCGGCGATGCGTGATCAGTACATGAGGACAGGCGAAGGATTTCTGTTG
          Q  E  E  Y  S  A  M  R  D  Q  Y  M  R  T  G  E  G  F  L  L
         GTTTTCGCCGTCAACGAGGCTAAATCTTTCGAGAATGTCGCTAACTACCGCGAGCAGATT
          V  F  A  V  N  E  A  K  S  F  E  N  V  A  N  Y  R  E  Q  I
         CGGAGGGTAAAGGATTCAGATGATGTTCCTATGGTCTTGGTAGGGAATAAATGTGATTTG
          R  R  V  K  D  S  D  D  V  P  M  V  L  V  G  N  K  C  D  L
         TCATCTCGATCAGTCGACTTCCGAACAGTCAGTGAGACAGCAAAGGGTTACGGTATTCCG
          S  S  R  S  V  D  F  R  T  V  S  E  T  A  K  G  Y  G  I  P
         AATGTCGACACATCTGCCAAAACGCGTATGGGAGTTGATGAAGCATTTTACACACTTGTT
          N  V  D  T  S  A  K  T  R  M  G  V  D  E  A  F  Y  T  L  V
         AGAGAAATTCGCAAGCATCGTGAGCGTCACGACAATAATAAGCCACAAAAGAAGAAGAAG
          R  E  I  R  K  H  R  E  R  H  D  N  N  K  P  Q  K  K  K  K
         TGTCAAATAATGTGA
          C  Q  I  M  -"""

ans = """ATGACGGAGTACAAGCTTGTGGTAGTTGGAGATGGAGGAGTTGGTAAATCAGCACTCACC
          M  T  E  Y  K  L  V  V  V  G  D  G  G  V  G  K  S  A  L  T
         ATTCAACTCATCCAGAATCACTTTGTCGAAGAATACGACCCGACCATAGAGGACAGCTAC
          I  Q  L  I  Q  N  H  F  V  E  E  Y  D  P  T  I  E  D  S  Y
         AGAAAGCAGGTTGTGATAGACGGTGAGACATGCCTCCTCGACATATTGGATACCGCCGGA
          R  K  Q  V  V  I  D  G  E  T  C  L  L  D  I  L  D  T  A  G
         CAAGAAGAATATTCGGCGATGCGTGATCAGTACATGAGGACAGGCGAAGGATTTCTGTTG
          Q  E  E  Y  S  A  M  R  D  Q  Y  M  R  T  G  E  G  F  L  L
         GTTTTCGCCGTCAACGAGGCTAAATCTTTCGAGAATGTCGCTAACTACCGCGAGCAGATT
          V  F  A  V  N  E  A  K  S  F  E  N  V  A  N  Y  R  E  Q  I
         CGGAGGGTAAAGGATTCAGATGATGTTCCTATGGTCTTGGTAGGGAATAAATGTGATTTG
          R  R  V  K  D  S  D  D  V  P  M  V  L  V  G  N  K  C  D  L
         TCATCTCGATCAGTCGACTTCCGAACAGTCAGTGAGACAGCAAAGGGTTACGGTATTCCG
          S  S  R  S  V  D  F  R  T  V  S  E  T  A  K  G  Y  G  I  P
         AATGTCGACACATCTGCCAAAACGCGTATGGGAGTTGATGAAGCATTTTACACACTTGTT
          N  V  D  T  S  A  K  T  R  M  G  V  D  E  A  F  Y  T  L  V
         AGAGAAATTCGCAAGCATCGTGAGCGTCACGACAATAATAAGCCACAAAAGAAGAAGAAG
          R  E  I  R  K  H  R  E  R  H  D  N  N  K  P  Q  K  K  K  K
         TGTCAAATAATGTGA
          C  Q  I  M  -"""
logic = sol == ans
print("5' to 3' Frame: 0")
print(logic)

# 5' to 3' Frame: 1
sol = """TGACGGAGTACAAGCTTGTGGTAGTTGGAGATGGAGGAGTTGGTAAATCAGCACTCACCA
          -  R  S  T  S  L  W  -  L  E  M  E  E  L  V  N  Q  H  S  P
         TTCAACTCATCCAGAATCACTTTGTCGAAGAATACGACCCGACCATAGAGGACAGCTACA
          F  N  S  S  R  I  T  L  S  K  N  T  T  R  P  -  R  T  A  T
         GAAAGCAGGTTGTGATAGACGGTGAGACATGCCTCCTCGACATATTGGATACCGCCGGAC
          E  S  R  L  -  -  T  V  R  H  A  S  S  T  Y  W  I  P  P  D
         AAGAAGAATATTCGGCGATGCGTGATCAGTACATGAGGACAGGCGAAGGATTTCTGTTGG
          K  K  N  I  R  R  C  V  I  S  T  -  G  Q  A  K  D  F  C  W
         TTTTCGCCGTCAACGAGGCTAAATCTTTCGAGAATGTCGCTAACTACCGCGAGCAGATTC
          F  S  P  S  T  R  L  N  L  S  R  M  S  L  T  T  A  S  R  F
         GGAGGGTAAAGGATTCAGATGATGTTCCTATGGTCTTGGTAGGGAATAAATGTGATTTGT
          G  G  -  R  I  Q  M  M  F  L  W  S  W  -  G  I  N  V  I  C
         CATCTCGATCAGTCGACTTCCGAACAGTCAGTGAGACAGCAAAGGGTTACGGTATTCCGA
          H  L  D  Q  S  T  S  E  Q  S  V  R  Q  Q  R  V  T  V  F  R
         ATGTCGACACATCTGCCAAAACGCGTATGGGAGTTGATGAAGCATTTTACACACTTGTTA
          M  S  T  H  L  P  K  R  V  W  E  L  M  K  H  F  T  H  L  L
         GAGAAATTCGCAAGCATCGTGAGCGTCACGACAATAATAAGCCACAAAAGAAGAAGAAGT
          E  K  F  A  S  I  V  S  V  T  T  I  I  S  H  K  R  R  R  S
         GTCAAATAATGT
          V  K  -  C"""

ans = """TGACGGAGTACAAGCTTGTGGTAGTTGGAGATGGAGGAGTTGGTAAATCAGCACTCACCA
          -  R  S  T  S  L  W  -  L  E  M  E  E  L  V  N  Q  H  S  P
         TTCAACTCATCCAGAATCACTTTGTCGAAGAATACGACCCGACCATAGAGGACAGCTACA
          F  N  S  S  R  I  T  L  S  K  N  T  T  R  P  -  R  T  A  T
         GAAAGCAGGTTGTGATAGACGGTGAGACATGCCTCCTCGACATATTGGATACCGCCGGAC
          E  S  R  L  -  -  T  V  R  H  A  S  S  T  Y  W  I  P  P  D
         AAGAAGAATATTCGGCGATGCGTGATCAGTACATGAGGACAGGCGAAGGATTTCTGTTGG
          K  K  N  I  R  R  C  V  I  S  T  -  G  Q  A  K  D  F  C  W
         TTTTCGCCGTCAACGAGGCTAAATCTTTCGAGAATGTCGCTAACTACCGCGAGCAGATTC
          F  S  P  S  T  R  L  N  L  S  R  M  S  L  T  T  A  S  R  F
         GGAGGGTAAAGGATTCAGATGATGTTCCTATGGTCTTGGTAGGGAATAAATGTGATTTGT
          G  G  -  R  I  Q  M  M  F  L  W  S  W  -  G  I  N  V  I  C
         CATCTCGATCAGTCGACTTCCGAACAGTCAGTGAGACAGCAAAGGGTTACGGTATTCCGA
          H  L  D  Q  S  T  S  E  Q  S  V  R  Q  Q  R  V  T  V  F  R
         ATGTCGACACATCTGCCAAAACGCGTATGGGAGTTGATGAAGCATTTTACACACTTGTTA
          M  S  T  H  L  P  K  R  V  W  E  L  M  K  H  F  T  H  L  L
         GAGAAATTCGCAAGCATCGTGAGCGTCACGACAATAATAAGCCACAAAAGAAGAAGAAGT
          E  K  F  A  S  I  V  S  V  T  T  I  I  S  H  K  R  R  R  S
         GTCAAATAATGT
          V  K  -  C"""
print("5' to 3' Frame: 1")
logic = sol == ans
print(logic)

# 5' to 3' Frame: 2
print("5' to 3' Frame: 2")
# print(logic)

# 3' to 5' Frame: 0
print("3' to 5' Frame: 0")
# print(logic)

# 3' to 5' Frame: 1
print("3' to 5' Frame: 1")
# print(logic)

# 3' to 5' Frame: 2
print("3' to 5' Frame: 2")
# print(logic)

print("-------------------")
